/**
 * Stable string codes attached to every {@link EngineError} thrown by the
 * engine. Codes are part of the public contract — user code is expected to
 * branch on them when handling engine failures — so renumbering or removing
 * a code is a breaking change.
 *
 * Each value is prefixed with a short domain tag (`COMP`, `PREFAB`, `DEP`,
 * `GAME`, `ASSET`, `RAND`, `GFX`) followed by a zero-padded sequence number,
 * so codes sort by domain and the wire format is stable across catalog growth.
 */
export enum ErrorCode {
  COMPONENT_NOT_FOUND = 'COMP001_COMPONENT_NOT_FOUND',
  COMPONENT_ALREADY_EXISTS = 'COMP002_COMPONENT_ALREADY_EXISTS',
  COMPONENT_AMBIGUOUS_TYPE = 'COMP003_COMPONENT_AMBIGUOUS_TYPE',
  PREFAB_INVALID_NAME = 'PREFAB001_PREFAB_INVALID_NAME',
  PREFAB_ALREADY_REGISTERED = 'PREFAB002_PREFAB_ALREADY_REGISTERED',
  PREFAB_NOT_FOUND = 'PREFAB003_PREFAB_NOT_FOUND',
  PREFAB_REGISTRY_NOT_ATTACHED = 'PREFAB004_PREFAB_REGISTRY_NOT_ATTACHED',
  PREFAB_BUILD_UNAUTHORIZED = 'PREFAB005_PREFAB_BUILD_UNAUTHORIZED',
  WORLD_COMPONENT_DEPENDENCY_MISSING = 'DEP001_WORLD_COMPONENT_DEPENDENCY_MISSING',
  WORLD_COMPONENT_DEPENDENCY_AMBIGUOUS = 'DEP002_WORLD_COMPONENT_DEPENDENCY_AMBIGUOUS',
  WORLD_COMPONENT_DEPENDENCY_REENTRANT = 'DEP003_WORLD_COMPONENT_DEPENDENCY_REENTRANT',
  GAME_WORLD_ALREADY_EXISTS = 'GAME001_GAME_WORLD_ALREADY_EXISTS',
  GAME_WORLD_NOT_FOUND = 'GAME002_GAME_WORLD_NOT_FOUND',
  ASSET_NOT_FOUND = 'ASSET001_ASSET_NOT_FOUND',
  ASSET_LOAD_FAILED = 'ASSET002_ASSET_LOAD_FAILED',
  ASSET_TYPE_MISMATCH = 'ASSET003_ASSET_TYPE_MISMATCH',
  ASSET_KEY_CONFLICT = 'ASSET004_ASSET_KEY_CONFLICT',
  RANDOM_EMPTY_ITEMS = 'RAND001_RANDOM_EMPTY_ITEMS',
  ANIMATED_SPRITE_EMPTY_FRAMES = 'GFX001_ANIMATED_SPRITE_EMPTY_FRAMES',
  AUDIO_UNAVAILABLE = 'AUDIO001_AUDIO_UNAVAILABLE',
  AUDIO_NO_SOURCE = 'AUDIO002_AUDIO_NO_SOURCE',
}
